config/routes.rb
Rails.application.routes.draw do
  
	root 'tasks#banks'
	  
	resources :recruiters  
	
	resources :tasks
	  
	get '/banks', to: 'tasks#banks'
	
	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]
	
	resources :faqs
  
	resources :posts do
		resources :comments
	end
	
	resources :pays
	
	resources :locations
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :name, presence: true
	belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message	  

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "ebitdada@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address       
	after_validation :geocode
end

app/models/pay.rb
class Pay < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true
	has_many :comments
end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :description, presence: true
	
	geocoded_by :address       
	after_validation :geocode
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		redirect_to post_path(@post)
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

def index
	@faqs = Faq.order('question ASC')
end

def new
	@faq = Faq.new
end

def create
	@faq = Faq.new(faq_params)
	@faq.save
	if @faq.save
		redirect_to faqs_path
	end
end

def edit
	@faq = Faq.find(params[:id])
end

def update
	@faq = Faq.find(params[:id])
	if @faq.update_attributes(faq_params)
		redirect_to faqs_path
	end
end

def faq_params
	params.require(:faq).permit(:question,:answer)
end



end

app/controllers/pays_controller.rb
class PaysController < ApplicationController

def index
	@pays = Pay.all
end

def show
	@pay = Pay.find(params[ :id])
end

def new
	@pay = Pay.new
end

def create
	@pay = Pay.new(pay_params)
	@pay.save
	if @pay.save
		redirect_to pays_path
	end
end

def edit
	@pay = Pay.find(params[:id])
end

def update
	@pay = Pay.find(params[:id])
	if @pay.update_attributes(pay_params)
		redirect_to pays_path
	end
end


def pay_params
	params.require(:pay).permit(:name, :analystbaselow, :analystbasehigh, :analystbonuslow, :analystbonushigh, :associatebaselow, :associatebasehigh, :associatebonuslow, :associatebonushigh, :vpbaselow, :vpbasehigh, :vpbonuslow, :vpbonushigh)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
	@posts = Post.order("created_at desc").limit(10)
end

def show
	@post = Post.find(params[:id])
	@posts = Post.order("created_at desc").limit(5)
end

def new
	@post = Post.new
end

def create
	@post = Post.new(post_params)
	@post.save
	if @post.save
		redirect_to posts_path
	end
end

def edit
	@post = Post.find(params[:id])
end

def update
	@post = Post.find(params[:id])
	if @post.update_attributes(post_params)
		redirect_to @post
	end
end

def post_params
	params.require(:post).permit(:description, :body)
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

def index
	@tasks = Task.order(:description)
end

def show
	@task = Task.find(params[ :id])
end

def new
	@task = Task.new
end

def create
	@task = Task.new(task_params)
	@task.save
	if @task.save
		redirect_to @task
	end
end

def edit
	@task = Task.find(params[:id])
end

def update
	@task = Task.find(params[:id])
	if @task.update_attributes(task_params)
		redirect_to @task
	end
end


def task_params
	params.require(:task).permit(:description, :des, :team_size, :location, :sector, :intern, :grad, :group, :uk_location, :rev13, :rev14, :rev15, :rev16, :analystpay, :associatepay, :vppay, :directorpay, :mdpay, :analystbonus, :associatebonus, :vpbonus, :directorbonus, :pros, :cons, :address, :latitude, :longitude)
  end
  
end

#@task = Task.find(params[ :id])

#https://www.youtube.com/watch?v=2zBS8NxHUJA

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="">
		<meta name="author" content="">

		<title>Off Canvas Template for Bootstrap</title>

		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">
		
	</head>

	<p class = "border">
	
		<p><%= comment.name %> (<%= comment.created_at.strftime("%b %d, %Y") %>)</p>

		<p><%= comment.body %></p>

	</p>
</html>




<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
<script src="offcanvas.js"></script>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %></br>
		<%= f.text_field :name %>
		
	</p>
	
	<p>
		<%= f.label :body %></br>
		<%= f.text_area :body %>
		
	</p>
	<p>
		<%= f.submit :Submit, class: 'btn btn-danger'%>
	</p>
	
<% end %>

app/views/contacts/create.html.erb
<h3 class = toppadding> Thank you for your message. </h3>

app/views/contacts/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="">
		<meta name="author" content="">

		<title>Bare - Start Bootstrap Template</title>

		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">
		
	</head>
		
	<body class = "toppadding">
		<div class="container"> 
			<h1>Contact us anonymously below</h1><br>
			
			<div class="col-sm-7">
	  
				<%= form_for @contact do |f| %>
				
				<p>
				<%= f.label "Name (optional)" %><br/>
				<%= f.text_field :name, :size => 50  %>
				</p>
				
				<p>
				<%= f.label "email (optional)" %><br/>
				<%= f.text_field :email,:size => 50 %>
				</p>
				
				<p>
				<%= f.label "Message" %><br/>
				<%= f.text_area :message, cols: "100", rows: "10" %>
				</p>
				
				<p>
				<%= f.submit "Send", class: "btn btn-danger" %>
				</p>
		
				<% end %>
			</div>
		</div>
	</body>

app/views/faqs/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="stylesheets/style.css" rel="stylesheet">
    
	<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="offcanvas.css" rel="stylesheet">
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
	
  </head>

	<body class = "toppadding">
	<div class="row" >
		<div class="col-md-6 col-md-offset-3">
				<%= form_for @faq do |x| %>
				  
				<p>
				<%= x.label :question %><br/>
				<%= x.text_field :question, class: 'form-control' %><br/>
				</p>
				
				<p>
				<%= x.label :answer %><br/>
				<%= x.text_field :answer, class: 'form-control' %><br/>
				</p>
				
				<p>
				<%= x.submit "Conform edit" %>
				</p>
				
				
				<% end %>
		</div>
	</div>
	</body>

app/views/faqs/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="">
		<meta name="author" content="">

		<title>Bare - Start Bootstrap Template</title>

		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">
		
	</head>
	
	<body class = "toppadding">
		<div class="container"> 
			<h1>Frequently asked questions</h1><br>
			
			<div class="col-sm-7">
				<% @faqs.each_with_index do |x, index| %>	
				<div class="panel-group">
					<div class="panel panel-default">
						
						<div class="panel-heading">
							<h4 class="panel-title"><a data-toggle="collapse" href="#collapse<%= index+1 %>"><%= x.question %></a></h4>
						</div>
						
						<div id="collapse<%= index+1 %>" class="panel-collapse collapse">
							<div class="panel-body"><%= x.answer %></div>
						</div>
							
					</div>
				</div>
				
				<% end %>
			
			</div>
			
			<div class="col-sm-5">
				<div class="well">
					<h5 class = "posttitle">Send us your questions anonymously</h5><br>
					<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
				</div>
			</div>	
			
		</div>
	</body>
</html>

	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="offcanvas.js"></script>
	</body>

app/views/faqs/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="stylesheets/style.css" rel="stylesheet">
    
	<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="offcanvas.css" rel="stylesheet">
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
	
  </head>

	<body class = "toppadding">
	<div class="row" >
		<div class="col-md-6 col-md-offset-3">
				<%= form_for @faq do |x| %>
				  
				<p>
				<%= x.label :question %><br/>
				<%= x.text_field :question, class: 'form-control' %><br/>
				</p>
				
				<p>
				<%= x.label :answer %><br/>
				<%= x.text_field :answer, class: 'form-control' %><br/>
				</p>
				
				<p>
				<%= x.submit "Add a new entry" %>
				</p>
				
				
				<% end %>
		</div>
	</div>
	</body>

app/views/pays/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Bare - Start Bootstrap Template</title>

	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="stylesheets/style.css" rel="stylesheet">

	
</head>

<body class="toppadding">
	<div class="container">
	
		<div class="row">
			<h1>Pay & bonus benchmarking</h1>
			<p class="lead"></p>
		</div>
		
		<div class="row">
			<div class="col-sm-7 text-left">
				<div class="table-responsive">
					
					<% @pays.each do |data| %>
					
					<table id="example" class="table table-hover">
						
							<h4>Pay & bonus <span class="label label-default"><%= data.name %></span></h4>
						
							<thead class = "tabletext">
								<tr>
								<th></th>
								<th>Base</th>
								<th></th>
								<th>Bonus</th>
								</tr>
							</thead>
						
							<tbody  class = "tabletext">
								<tr>
								<th>Analyst</th>
								<td><%= "£" + number_with_delimiter(data.analystbaselow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.analystbasehigh.to_s, :delimiter => ',') %></td>
								<td><p>plus</p></td>
								<td><%= "£" + number_with_delimiter(data.analystbonuslow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.analystbonushigh.to_s, :delimiter => ',') %></td>
								</tr>
								
								<tr>
								<th>Associate</th>
								<td><%= "£" + number_with_delimiter(data.associatebaselow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.associatebasehigh.to_s, :delimiter => ',') %></td>
								<td><p>plus</p></td>
								<td><%= "£" + number_with_delimiter(data.associatebonuslow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.associatebonushigh.to_s, :delimiter => ',') %></td>
								</tr>
								
								<tr>
								<th>VP</th>
								<td><%= "£" + number_with_delimiter(data.vpbaselow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.vpbasehigh.to_s, :delimiter => ',') %></td>
								<td><p>plus</p></td>
								<td><%= "£" + number_with_delimiter(data.vpbonuslow.to_s, :delimiter => ',') + " - " + "£" + number_with_delimiter(data.vpbonushigh.to_s, :delimiter => ',') %></td>
								</tr>
								<% end %>
							</tbody>
					
					</table>	
				</div>
				
				
				
			</div>
		
			<div class="col-sm-5">
				
				<div class="well">
					<dl>Bonuses vary by firm and by year, as well as being subject to differing mixes of cash vs stock vs deferred</dl>
					<dl>The ranges opposite ignore outliers, in particular zero bonuses which are often used to encourage underperformers to leave</dl>
				</div>
				
				<div class="well">
					<h5 class = "posttitle">Help us keep our information up to date - share insight into your firm anonymously</h5><br>
					<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="">
		<meta name="author" content="">

		<title>Bare - Start Bootstrap Template</title>

		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">
		
	</head>
	
	<body class = "toppadding">
		<div class="container"> 
			<h1>Insight and views</h1><br>
			
			<div class="col-sm-8">
				<% @posts.each do |x| %>					
					<p class = "border">
					<h5 class = "postdate"><%= x.created_at.strftime("%b %d, %Y") %></h5>
					<h4 class = "posttitle"><%= x.description %></h4>
					<p><%= truncate(x.body, length: 200, separator: ' ') %></p>
					<p><a href="<%= post_path(x) %>">>> READ MORE</a></p>
				</p>
				<% end %>	
			</div>
		
			<div class="col-sm-4">
				<div class="well">
					<h5 class = "posttitle">Help contribute or share your views anonymously</h5><br>
					<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
				</div>
			</div>
		
		</div>
	</body>
</html>

	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="offcanvas.js"></script>
	</body>

app/views/tasks/banks.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">

	</head>

	<body>
		<section class = "sectioncolourone">
			<div class="container">
				<div class="row">
					<div class="col-sm-2"  align = "center">
					</div>
					<div class="col-sm-2"  align = "center">
						<%= link_to tasks_path do
							image_tag("list-xxl-grey.png", onmouseover: "this.src='#{asset_path('list-xxl-black.png')}'", onmouseout: "this.src='#{asset_path('list-xxl-grey.png')}'",:size => "120x120")
							end %>
						<div class="caption">
						<h3>M&A Advisors</h3>
						</div>
					</div>
					
					<div class="col-sm-2"  align = "center">
						<%= link_to pays_path do
							image_tag("bonus-grey.png", onmouseover: "this.src='#{asset_path('bonus-black.png')}'", onmouseout: "this.src='#{asset_path('bonus-grey.png')}'",:size => "120x120")
							end %>
						<div class="caption">
						<h3>Pay & Bonus</h3>
						</div>
					</div>
					
					<div class="col-sm-2" align = "center">
						<%= link_to recruiters_path do
							image_tag("recruit-grey.png", onmouseover: "this.src='#{asset_path('recruit-black.png')}'", onmouseout: "this.src='#{asset_path('recruit-grey.png')}'",:size => "120x120")
							end %>
						<div class="caption">
						<h3>Recruiters</h3>
						</div>
					</div>
					
					<div class="col-sm-2" align = "center">
						<%= link_to posts_path do
							image_tag("Insight-grey.png", onmouseover: "this.src='#{asset_path('Insight-black.png')}'", onmouseout: "this.src='#{asset_path('Insight-grey.png')}'",:size => "120x120")
							end %>
						<div class="caption">
						<h3>Tips & Insight</h3>
						</div>
					</div>
					
					<div class="col-sm-2"  align = "center">
					</div>	
				</div>
			</div>	
		</section>
		
		<section class = "sectioncolourtwo">
			<div class="container">
				<div class="row">
				
					<div class="col-sm-4">
					<%= render partial: 'posts/post', locals: { post: Post.last } %>
					</div>
				
					<div class="col-sm-4">
					<%= render partial: 'posts/post', locals: { post: Post.last } %>
					</div>
					
					<div class="col-sm-4">
						<div class="well">
						<h5 class = "posttitle">Send news and views to our team using our anonymous form</h5><br>
						<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
						</div>
					</div>
					
				</div>
			</div>
		</section>
	</body>
</html>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Bare - Start Bootstrap Template</title>

	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="stylesheets/style.css" rel="stylesheet">

	
</head>

<body class="toppadding">
	<div class="container">
	
		<div class="row">
			<h1>Listing of leading UK M&A advisors</h1>
			<p class="lead"></p>
		</div>
		
		<div class="row">
			<div class="col-sm-8 text-left">
				<div class="table-responsive">
					<table id="example" class="table table-hover">
						<thead class = "tabletext">                         
							<tr>                          
								<th>Name</th>
								<th>Type</th>
								<th>UK Team size</th>
								<th>Sector Focus</th>
							</tr>
						</thead>
	
						<tbody class = "tabletext">
							<% @tasks.each do |data| %>       
								<tr class="clickable-row" data-href='<%= task_path(data)%>'>
									<td><%= data.description %></td>  
									<td><%= data.group %></td>
									<td><%= data.team_size %></td>
									<td><%= data.sector %></td>
									</tr>
								<% end %>
						</tbody>
					
					<script>
						jQuery(document).ready(function($) {
						$(".clickable-row").click(function() {
						window.location = $(this).data("href");
						});
						});
					</script>	
					
					</table>	
				</div>
			</div>
		
			<div class="col-sm-4">
				<div class="well">
					<h5 class = "posttitle">Is your firm missing or do you have information to share? Let us know</h5><br>
					<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

<!-- class='clickable-row' data-href='tasks/9' -->

app/views/tasks/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="stylesheets/style.css" rel="stylesheet">

	</head>

	<body class = "toppadding">
		<div class="container">
				
				<h1><%= @task.description %></h1>
				<span class="label label-default"><%= @task.group %></span>
				<span class="label label-default"><%= @task.location %></span>
				<span class="label label-default"><%= @task.sector %></span>
		
			 
			<div class="row">
				<div class="col-sm-6">
					<h3>The Basics</h3>
					<table class="table table-hover">
						<tbody class = "tabletext">
							
							<tr>
							<td>UK team size</td>
							<td><%= @task.team_size %></td>
							</tr>	
							
							<tr>
							<td>UK office(s)</td>
							<td><%= @task.uk_location %></td>
							</tr>
  
							<tr>
							<td>Internships:</td>
							<td><%= @task.intern %></td>									
							</tr>
							
							<tr>
							<td>Graduates:</td>
							<td><%= @task.grad %></td>
							</tr>	
						
							<tr>
							<td>How to apply:</td>
							<td><%= @task.cons %></td>
							</tr>	
						
						</tbody>
					</table>
					
					<h3>Insight</h3>
					<div class="panel panel-footer">
							<div class="panel-body">								
							<tr>
							<td><small><%= simple_format(@task.pros) %></small></td>
							</tr>
							</div>
					</div>
					
				</div>		
						
				<div class="col-sm-6">
					<!-- Code below left unaltered from google example -->
					<h3>Location</h3><p><%= @task.address %></p>
					<meta name="viewport" content="initial-scale=1.0">
					<meta charset="utf-8">
					<style>
					  #map {
						height: 100%;
					  }
					  
					  html, body {
						height: 80%;
						margin: 0;
						padding: 0;
					  }
					</style>
					  
					<body>
					<div id="map"></div>
					<script>
						function initMap() {
							var myCenter = new google.maps.LatLng(<%= @task.latitude %>,<%= @task.longitude %>);
							var mapCanvas = document.getElementById("map");
							var mapOptions = {center: myCenter, zoom: 15};
							var map = new google.maps.Map(mapCanvas, mapOptions);
							var marker = new google.maps.Marker({position:myCenter});
							marker.setMap(map);
						}	
					</script>
					
					<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDd92RusGDj-ImHWHaUQu-3FRKwD1wg5DU&callback=initMap"async defer>
					</script>
					</body>
						
					<br>
					
					<div class="well">
					<h5 class = "posttitle">Something to add, or something missing? Contact us anonymously</h5><br>
					<%= link_to "Click here", contacts_path, class: "btn btn-danger" %>
					</div>
					
				</div>			
			</div>
					
		</div>
			
		</div><!--/row-->
	</body>
</html>

	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="offcanvas.js"></script>